### ISSUE TITLE
an error occurred when i enter the test command you provided in Readme.md

### ISSUE THREAD

**Issue by Hsuweehou** [tjiiv-cprg/MonoRUn#4]
Thank you for your amazing job!

I ve got an error log below when i entered the test command as follow ' python test.py configs/kitti_multiclass.py checkpoints/kitti_multiclass.pth --val-set --gpu-ids 0'

seems like mmdet causes these, plz help me with it.

/home/coreesac/Hsuweehowe/proj/MonoRUn/mmdetection/mmdet/models/builder.py:56: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/monorun/models/necks/fpn_plus.py", line 41, in __init__
    upsample_cfg)
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/mmdetection/mmdet/models/necks/fpn.py", line 86, in __init__
    self.upsample_cfg = upsample_cfg.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/mmdetection/mmdet/models/detectors/two_stage.py", line 35, in __init__
    self.neck = build_neck(neck)
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/mmdetection/mmdet/models/builder.py", line 25, in build_neck
    return NECKS.build(cfg)
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: FPNplus: 'NoneType' object has no attribute 'copy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 83, in <module>
    main()
  File "test.py", line 79, in main
    tools.test.main()
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/tools/test.py", line 174, in main
    model = build_detector(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
  File "/home/coreesac/Hsuweehowe/proj/MonoRUn/mmdetection/mmdet/models/builder.py", line 62, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/coreesac/anaconda3/envs/MonoRUn1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: MonoRUnDetector: FPNplus: 'NoneType' object has no attribute 'copy'

**Comment by Hsuweehou** [comment]
turns out it is an version mismatch error.
